export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_ROBOTS_PENDING = "REQEUST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQEUST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQEUST_ROBOTS_FAILED";
